### ISSUE TITLE
dependency error - Need to update `github.com/IBM/go-sdk-core/v3/` to `github.com/IBM/go-sdk-core/v4/`

### ISSUE THREAD

**Issue by Bhagyashreek8** [IBM/ibm-cos-sdk-go-config#2]
Issue -
package `github.com/IBM/go-sdk-core/` has been updated to v4.
This is causing dependency issues when using `github.com/IBM/ibm-cos-sdk-go-config/resourceconfigurationv1`

Solution -
Need to update the dependency in go.mod 
https://github.com/IBM/ibm-cos-sdk-go-config/blob/master/go.mod#L6

**Comment by Bhagyashreek8** [comment]
using v3 version of `github.com/IBM/go-sdk-core/` as a workaround.
But it will be good to use v4 which has fix for Base Service.

**Comment by sandersrIBM** [comment]
@Bhagyashreek8 - We are tracking this issue internally.  We will update here once more is known.

**Comment by sandersrIBM** [comment]
As mentioned, we are tracking this issue internally.  A fix will be included in the next release.  Closing issue.
